# Generated by Django 5.2.4 on 2025-08-01 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='aadhar',
            new_name='aadhar_back',
        ),
        migrations.AddField(
            model_name='customuser',
            name='aadhar_front',
            field=models.FileField(blank=True, null=True, upload_to='documents/aadhar/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='no_license',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='documents/profile_pictures/'),
        ),
    ]
